export let styles = [
  { value: 'Amber Ale', display: 'Amber Ale'},
  { value: 'Barleywine', display: 'Barleywine'},
  { value: 'Belgian Wit', display: 'Belgian Wit'},
  { value: 'Brown', display: 'Brown'},
  { value: 'Cider', display: 'Cider'},
  { value: 'Double IPA', display: 'Double IPA'},
  { value: 'Hefeweizen', display: 'Hefeweizen'},
  { value: 'IPA', display: 'IPA'},
  { value: 'Lager', display: 'Lager'},
  { value: 'Pale Ale', display: 'Pale Ale'},
  { value: 'Porter', display: 'Porter'},
  { value: 'Pilsner', display: 'Pilsner'},
  { value: 'Red Ale', display: 'Red Ale'},
  { value: 'Saison', display: 'Saison'},
  { value: 'Sour Ale', display: 'Sour Ale'},
  { value: 'Stout', display: 'Stout'},
  { value: 'Wheat', display: 'Wheat'},
];
